[package]
name = "jacopone"
version = "0.2.0"
authors = ["zeegomo <g.pasini98@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Jacopone implementation in Rust"
edition = "2018"

[dependencies]
openssl = {version = "0.10.28", features = ["vendored"]}
crunchy = "0.2.2"
